import { ProductMatrixDTO } from '../../../../types/serverInterface/ProductMatrixDTO';

export const productMatrix: ProductMatrixDTO = [
  // Row 1 (5 cells)
  {
    id: 1,
    rowNumber: 1,
    cellNumber: 1,
    price: 75,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Lays',
    productName: 'Чипсы Classic 70г',
    calories: 520,
    proteins: 6,
    fats: 33,
    carbohydrates: 50,
    description: 'Классические картофельные чипсы, слегка солёные.',
  },
  {
    id: 2,
    rowNumber: 1,
    cellNumber: 2,
    price: 65,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Snickers',
    productName: 'Батончик Snickers 50г',
    calories: 250,
    proteins: 4,
    fats: 12,
    carbohydrates: 32,
    description: 'Шоколадный батончик с нугой, карамелью и арахисом.',
  },
  {
    id: 3,
    rowNumber: 1,
    cellNumber: 3,
    price: 80,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Pringles',
    productName: 'Чипсы Pringles Original 110г',
    calories: 520,
    proteins: 6,
    fats: 35,
    carbohydrates: 52,
    description: 'Хрустящие чипсы в характерной банке.',
  },
  {
    id: 4,
    rowNumber: 1,
    cellNumber: 4,
    price: 55,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Bounty',
    productName: 'Батончик Bounty 57г',
    calories: 279,
    proteins: 2,
    fats: 14,
    carbohydrates: 36,
    description: 'Кокосовый батончик в молочном шоколаде.',
  },
  {
    id: 5,
    rowNumber: 1,
    cellNumber: 5,
    price: 60,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Oreo',
    productName: 'Печенье Oreo 95г',
    calories: 480,
    proteins: 6,
    fats: 18,
    carbohydrates: 70,
    description: 'Шоколадное печенье с кремовой начинкой.',
  },

  // Row 2 (5 cells)
  {
    id: 6,
    rowNumber: 2,
    cellNumber: 6,
    price: 90,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Doritos',
    productName: 'Doritos Nacho 75г',
    calories: 480,
    proteins: 7,
    fats: 24,
    carbohydrates: 58,
    description: 'Кукурузные чипсы с сырным вкусом.',
  },
  {
    id: 7,
    rowNumber: 2,
    cellNumber: 7,
    price: 70,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'KitKat',
    productName: 'KitKat 4-finger 41.5г',
    calories: 208,
    proteins: 2,
    fats: 11,
    carbohydrates: 25,
    description: 'Хрустящие вафельные пластинки в шоколаде.',
  },
  {
    id: 8,
    rowNumber: 2,
    cellNumber: 8,
    price: 120,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Pringles',
    productName: 'Pringles Sour Cream 150г',
    calories: 530,
    proteins: 5,
    fats: 34,
    carbohydrates: 52,
    description: 'Чипсы со вкусом сметаны и зелени.',
  },
  {
    id: 9,
    rowNumber: 2,
    cellNumber: 9,
    price: 85,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Twix',
    productName: 'Twix Twin 50г',
    calories: 244,
    proteins: 2,
    fats: 12,
    carbohydrates: 33,
    description: 'Два хрустящих печенья с карамелью в шоколаде.',
  },
  {
    id: 10,
    rowNumber: 2,
    cellNumber: 10,
    price: 95,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Cheetos',
    productName: 'Cheetos Puffs 70г',
    calories: 480,
    proteins: 6,
    fats: 25,
    carbohydrates: 53,
    description: 'Сырные кукурузные палочки.',
  },

  // Row 3 (5 cells)
  {
    id: 11,
    rowNumber: 3,
    cellNumber: 11,
    price: 150,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'FitBar',
    productName: 'Протеиновый батончик 50г',
    calories: 200,
    proteins: 20,
    fats: 8,
    carbohydrates: 12,
    description: 'Высокобелковый батончик для перекуса.',
  },
  {
    id: 12,
    rowNumber: 3,
    cellNumber: 12,
    price: 50,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: "M&M's",
    productName: "M&M's Milk Chocolate 45г",
    calories: 230,
    proteins: 3,
    fats: 11,
    carbohydrates: 30,
    description: 'Шоколадные драже в цветной оболочке.',
  },
  {
    id: 13,
    rowNumber: 3,
    cellNumber: 13,
    price: 110,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Popcorn',
    productName: 'Попкорн сладкий 90г',
    calories: 450,
    proteins: 5,
    fats: 18,
    carbohydrates: 62,
    description: 'Сладкий карамельный попкорн.',
  },
  {
    id: 14,
    rowNumber: 3,
    cellNumber: 14,
    price: 140,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Nuts&More',
    productName: 'Микс орехов 100г',
    calories: 620,
    proteins: 16,
    fats: 54,
    carbohydrates: 18,
    description: 'Арахис, миндаль и кешью в лёгкой соли.',
  },
  {
    id: 15,
    rowNumber: 3,
    cellNumber: 15,
    price: 65,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Milka',
    productName: 'Milka Alpine Milk 100г',
    calories: 540,
    proteins: 6,
    fats: 30,
    carbohydrates: 58,
    description: 'Шоколад молочный, классический.',
  },

  // Row 4 (10 cells)
  {
    id: 16,
    rowNumber: 4,
    cellNumber: 16,
    price: 95,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Kinder',
    productName: 'Kinder Bueno 43г',
    calories: 240,
    proteins: 3,
    fats: 13,
    carbohydrates: 26,
    description: 'Шоколадный батончик с кремовой начинкой.',
  },
  {
    id: 17,
    rowNumber: 4,
    cellNumber: 17,
    price: 80,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'GoodSnacks',
    productName: "Печёные чипсы 'Сыр' 60г",
    calories: 360,
    proteins: 6,
    fats: 12,
    carbohydrates: 48,
    description: 'Более лёгкая альтернатива обычным чипсам.',
  },
  {
    id: 18,
    rowNumber: 4,
    cellNumber: 18,
    price: 120,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'NatureTrail',
    productName: 'Сухофрукты и орехи 120г',
    calories: 550,
    proteins: 8,
    fats: 30,
    carbohydrates: 52,
    description: 'Смесь из изюма, клюквы и орехов.',
  },
  {
    id: 19,
    rowNumber: 4,
    cellNumber: 19,
    price: 70,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Haribo',
    productName: 'Haribo Goldbears 80г',
    calories: 320,
    proteins: 5,
    fats: 0,
    carbohydrates: 75,
    description: 'Жевательные мармеладные мишки.',
  },
  {
    id: 20,
    rowNumber: 4,
    cellNumber: 20,
    price: 130,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Crispy',
    productName: 'Рисовые хлебцы с шоколадом 100г',
    calories: 420,
    proteins: 7,
    fats: 12,
    carbohydrates: 70,
    description: 'Легкие хлебцы в шоколадной глазури.',
  },
  {
    id: 21,
    rowNumber: 4,
    cellNumber: 21,
    price: 160,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Boost',
    productName: 'Энергетик 250мл',
    calories: 110,
    proteins: 0,
    fats: 0,
    carbohydrates: 28,
    description: 'Газированный энергетический напиток.',
  },
  {
    id: 22,
    rowNumber: 4,
    cellNumber: 22,
    price: 95,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Granola',
    productName: 'Снэк-бар мюсли 50г',
    calories: 210,
    proteins: 4,
    fats: 8,
    carbohydrates: 28,
    description: 'Полезный перекус из злаков и мёда.',
  },
  {
    id: 23,
    rowNumber: 4,
    cellNumber: 23,
    price: 75,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'SeaBite',
    productName: 'Снэк нори 10г',
    calories: 40,
    proteins: 3,
    fats: 2,
    carbohydrates: 1,
    description: 'Хрустящие листы водорослей.',
  },
  {
    id: 24,
    rowNumber: 4,
    cellNumber: 24,
    price: 140,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: "Baker's",
    productName: 'Солёные крендели 120г',
    calories: 450,
    proteins: 10,
    fats: 6,
    carbohydrates: 80,
    description: 'Хрустящие крендели с солью.',
  },
  {
    id: 25,
    rowNumber: 4,
    cellNumber: 25,
    price: 180,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'DeliSnack',
    productName: 'Мини-сэндвич с курицей',
    calories: 320,
    proteins: 18,
    fats: 12,
    carbohydrates: 30,
    description: 'Свежий мини-сэндвич — быстрый перекус.',
  },

  // Row 5 (10 cells)
  {
    id: 26,
    rowNumber: 5,
    cellNumber: 26,
    price: 95,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'HealthyBites',
    productName: 'Овсяное печенье 80г',
    calories: 380,
    proteins: 6,
    fats: 12,
    carbohydrates: 58,
    description: 'Домашний вкус, с кусочками овса.',
  },
  {
    id: 27,
    rowNumber: 5,
    cellNumber: 27,
    price: 60,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Fruity',
    productName: 'Жевательные конфеты 70г',
    calories: 300,
    proteins: 1,
    fats: 0,
    carbohydrates: 75,
    description: 'Фруктовые мармеладки, без косточек.',
  },
  {
    id: 28,
    rowNumber: 5,
    cellNumber: 28,
    price: 110,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'JerkyCo',
    productName: 'Вяленая говядина 50г',
    calories: 180,
    proteins: 30,
    fats: 4,
    carbohydrates: 3,
    description: 'Богатый белком мясной снек.',
  },
  {
    id: 29,
    rowNumber: 5,
    cellNumber: 29,
    price: 85,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'ChocoCup',
    productName: 'Шоколадный кекс 90г',
    calories: 370,
    proteins: 4,
    fats: 18,
    carbohydrates: 48,
    description: 'Нежный кекс в индивидуальной упаковке.',
  },
  {
    id: 30,
    rowNumber: 5,
    cellNumber: 30,
    price: 55,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Fresh',
    productName: 'Жевательная резинка 14г',
    calories: 5,
    proteins: 0,
    fats: 0,
    carbohydrates: 1,
    description: 'Освежает дыхание.',
  },
  {
    id: 31,
    rowNumber: 5,
    cellNumber: 31,
    price: 125,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'BioAct',
    productName: 'Йогурт питьевой 250мл',
    calories: 150,
    proteins: 6,
    fats: 3,
    carbohydrates: 24,
    description: 'Пробиотический йогурт для лёгкого перекуса.',
  },
  {
    id: 32,
    rowNumber: 5,
    cellNumber: 32,
    price: 135,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'DeliSnack',
    productName: 'Мини-сэндвич с салями',
    calories: 360,
    proteins: 14,
    fats: 18,
    carbohydrates: 28,
    description: 'Сытный мини-сэндвич.',
  },
  {
    id: 33,
    rowNumber: 5,
    cellNumber: 33,
    price: 90,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'CrunchyFruits',
    productName: 'Чипсы из яблок 40г',
    calories: 170,
    proteins: 0,
    fats: 0,
    carbohydrates: 42,
    description: 'Сухофрукты, хрустящие ломтики яблока.',
  },
  {
    id: 34,
    rowNumber: 5,
    cellNumber: 34,
    price: 150,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Nuts&More',
    productName: 'Соленый арахис 120г',
    calories: 670,
    proteins: 25,
    fats: 50,
    carbohydrates: 20,
    description: 'Классический солёный арахис.',
  },
  {
    id: 35,
    rowNumber: 5,
    cellNumber: 35,
    price: 220,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'FreshBite',
    productName: 'Мини-суши набор (6шт)',
    calories: 300,
    proteins: 10,
    fats: 6,
    carbohydrates: 48,
    description: 'Свежие мини-суши, срок хранения короткий.',
  },

  // Row 6 (10 cells)
  {
    id: 36,
    rowNumber: 6,
    cellNumber: 36,
    price: 170,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'DeliSnack',
    productName: 'Сэндвич с ветчиной и сыром',
    calories: 420,
    proteins: 20,
    fats: 18,
    carbohydrates: 38,
    description: 'Классический холодный сэндвич.',
  },
  {
    id: 37,
    rowNumber: 6,
    cellNumber: 37,
    price: 125,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'FreshFruits',
    productName: 'Стакан с фруктами 200г',
    calories: 90,
    proteins: 1,
    fats: 0,
    carbohydrates: 22,
    description: 'Нарезанные сезонные фрукты.',
  },
  {
    id: 38,
    rowNumber: 6,
    cellNumber: 38,
    price: 140,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Cheesy',
    productName: 'Сырные палочки 80г',
    calories: 330,
    proteins: 16,
    fats: 24,
    carbohydrates: 6,
    description: 'Палочки из плавленого сыра, готовый перекус.',
  },
  {
    id: 39,
    rowNumber: 6,
    cellNumber: 39,
    price: 55,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'AquaPure',
    productName: 'Вода питьевая 0.5л',
    calories: 0,
    proteins: 0,
    fats: 0,
    carbohydrates: 0,
    description: 'Негазированная питьевая вода.',
  },
  {
    id: 40,
    rowNumber: 6,
    cellNumber: 40,
    price: 160,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'DeliSnack',
    productName: 'Ролл с курицей',
    calories: 380,
    proteins: 22,
    fats: 14,
    carbohydrates: 34,
    description: 'Лёгкий ролл с соусом.',
  },
  {
    id: 41,
    rowNumber: 6,
    cellNumber: 41,
    price: 95,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'Mars',
    productName: 'Mars Bar Large 62г',
    calories: 280,
    proteins: 3,
    fats: 12,
    carbohydrates: 40,
    description: 'Большая версия классического Mars.',
  },
  {
    id: 42,
    rowNumber: 6,
    cellNumber: 42,
    price: 100,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'TeaTime',
    productName: 'Холодный зелёный чай 330мл',
    calories: 20,
    proteins: 0,
    fats: 0,
    carbohydrates: 5,
    description: 'Освежающий холодный чай без сахара.',
  },
  {
    id: 43,
    rowNumber: 6,
    cellNumber: 43,
    price: 210,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'FreshBite',
    productName: 'Салат Цезарь 250г',
    calories: 320,
    proteins: 12,
    fats: 20,
    carbohydrates: 12,
    description: 'Свежий салат с курицей и соусом.',
  },
  {
    id: 44,
    rowNumber: 6,
    cellNumber: 44,
    price: 65,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'SweetHome',
    productName: 'Мини-печенье ассорти 60г',
    calories: 300,
    proteins: 3,
    fats: 12,
    carbohydrates: 42,
    description: 'Небольшой пакетик печенья для перекуса.',
  },
  {
    id: 45,
    rowNumber: 6,
    cellNumber: 45,
    price: 190,
    imgPath: 'https://storage.yandexcloud.net/dev-product-img/54/Вода_негаз_54_5',
    brandName: 'DeliHeat',
    productName: 'Тёплый панини с ветчиной',
    calories: 450,
    proteins: 22,
    fats: 20,
    carbohydrates: 38,
    description: 'Горячий панини, готов к употреблению.',
  },
];
